package com.Exceptions;

import java.io.FileNotFoundException; 

import java.io.IOException; 

public class ExceptionInterviewQuestion_01 {

	public static void main(String[] args) {
		try { 

			multiple(); 

			}
		catch (FileNotFoundException | IOException ex) { 

			e.printStackTrace(); 

			} 

			} 

			public static void multiple() throws IOException, FileNotFoundException{ 

			System.out.println("Inside multiple"); 

			 

			

	


	

	}

}
